In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv(r'/content/WA_Fn-UseC_-HR-Employee-Attrition.csv')
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [4]:
df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [5]:
cols=["BusinessTravel" ,"Department" ,"EducationField" ,"Gender" ,"JobRole" ,"MaritalStatus", "Over18" ,"OverTime","Attrition"]
newdf=pd.get_dummies(df[cols])
newdf

,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,EducationField_Human Resources,EducationField_Life Sciences,EducationField_Marketing,EducationField_Medical,...,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes,Attrition_No,Attrition_Yes
0,0,0,1,0,0,1,0,1,0,0,...,1,0,0,0,1,1,0,1,0,1
1,0,1,0,0,1,0,0,1,0,0,...,0,0,0,1,0,1,1,0,1,0
2,0,0,1,0,1,0,0,0,0,0,...,0,0,0,0,1,1,0,1,0,1
3,0,1,0,0,1,0,0,1,0,0,...,0,0,0,1,0,1,0,1,1,0
4,0,0,1,0,1,0,0,0,0,1,...,0,0,0,1,0,1,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,0,1,0,0,1,0,0,0,0,1,...,0,0,0,1,0,1,1,0,1,0
1466,0,0,1,0,1,0,0,0,0,1,...,0,0,0,1,0,1,1,0,1,0
1467,0,0,1,0,1,0,0,1,0,0,...,0,0,0,1,0,1,0,1,1,0
1468,0,1,0,0,0,1,0,0,0,1,...,1,0,0,1,0,1,1,0,1,0
1469,0,0,1,0,1,0,0,0,0,1,...,0,0,0,1,0,1,1,0,1,0

In [6]:
df.drop(cols,axis=1,inplace=True)
df=pd.concat([df,newdf],axis=1)
df.drop("EmployeeNumber",inplace=True,axis=1)
df

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,...,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes,Attrition_No,Attrition_Yes
0,41,1102,1,2,1,2,94,3,2,4,...,1,0,0,0,1,1,0,1,0,1
1,49,279,8,1,1,3,61,2,2,2,...,0,0,0,1,0,1,1,0,1,0
2,37,1373,2,2,1,4,92,2,1,3,...,0,0,0,0,1,1,0,1,0,1
3,33,1392,3,4,1,4,56,3,1,3,...,0,0,0,1,0,1,0,1,1,0
4,27,591,2,1,1,1,40,3,1,2,...,0,0,0,1,0,1,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,884,23,2,1,3,41,4,2,4,...,0,0,0,1,0,1,1,0,1,0
1466,39,613,6,1,1,4,42,2,3,1,...,0,0,0,1,0,1,1,0,1,0
1467,27,155,4,3,1,2,87,4,2,2,...,0,0,0,1,0,1,0,1,1,0
1468,49,1023,2,3,1,4,63,2,2,2,...,1,0,0,1,0,1,1,0,1,0
1469,34,628,8,3,1,2,82,4,2,3,...,0,0,0,1,0,1,1,0,1,0

In [7]:
encodedcols=["HourlyRate", "MonthlyIncome", "MonthlyRate"]
encodeddf=df[encodedcols]
encodeddf
df

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,...,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes,Attrition_No,Attrition_Yes
0,41,1102,1,2,1,2,94,3,2,4,...,1,0,0,0,1,1,0,1,0,1
1,49,279,8,1,1,3,61,2,2,2,...,0,0,0,1,0,1,1,0,1,0
2,37,1373,2,2,1,4,92,2,1,3,...,0,0,0,0,1,1,0,1,0,1
3,33,1392,3,4,1,4,56,3,1,3,...,0,0,0,1,0,1,0,1,1,0
4,27,591,2,1,1,1,40,3,1,2,...,0,0,0,1,0,1,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,884,23,2,1,3,41,4,2,4,...,0,0,0,1,0,1,1,0,1,0
1466,39,613,6,1,1,4,42,2,3,1,...,0,0,0,1,0,1,1,0,1,0
1467,27,155,4,3,1,2,87,4,2,2,...,0,0,0,1,0,1,0,1,1,0
1468,49,1023,2,3,1,4,63,2,2,2,...,1,0,0,1,0,1,1,0,1,0
1469,34,628,8,3,1,2,82,4,2,3,...,0,0,0,1,0,1,1,0,1,0

In [8]:
from sklearn.preprocessing import MinMaxScaler
ms=MinMaxScaler()
x_scaled=pd.DataFrame(ms.fit_transform(encodeddf),columns=encodeddf.columns)
x_scaled

      HourlyRate  MonthlyIncome  MonthlyRate
0       0.914286       0.262454     0.698053
1       0.442857       0.217009     0.916001
2       0.885714       0.056925     0.012126
3       0.371429       0.100053     0.845814
4       0.142857       0.129489     0.583738
...          ...            ...          ...
1465    0.157143       0.082254     0.409396
1466    0.171429       0.472986     0.777474
1467    0.814286       0.270300     0.123670
1468    0.471429       0.230700     0.447661
1469    0.742857       0.178778     0.326601

[1470 rows x 3 columns]

In [9]:
df.drop(encodedcols,axis=1,inplace=True)
df=pd.concat([df,x_scaled],axis=1)
df

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EnvironmentSatisfaction,JobInvolvement,JobLevel,JobSatisfaction,NumCompaniesWorked,...,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes,Attrition_No,Attrition_Yes,HourlyRate,MonthlyIncome,MonthlyRate
0,41,1102,1,2,1,2,3,2,4,8,...,0,1,1,0,1,0,1,0.914286,0.262454,0.698053
1,49,279,8,1,1,3,2,2,2,1,...,1,0,1,1,0,1,0,0.442857,0.217009,0.916001
2,37,1373,2,2,1,4,2,1,3,6,...,0,1,1,0,1,0,1,0.885714,0.056925,0.012126
3,33,1392,3,4,1,4,3,1,3,1,...,1,0,1,0,1,1,0,0.371429,0.100053,0.845814
4,27,591,2,1,1,1,3,1,2,9,...,1,0,1,1,0,1,0,0.142857,0.129489,0.583738
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,884,23,2,1,3,4,2,4,4,...,1,0,1,1,0,1,0,0.157143,0.082254,0.409396
1466,39,613,6,1,1,4,2,3,1,4,...,1,0,1,1,0,1,0,0.171429,0.472986,0.777474
1467,27,155,4,3,1,2,4,2,2,1,...,1,0,1,0,1,1,0,0.814286,0.270300,0.123670
1468,49,1023,2,3,1,4,2,2,2,2,...,1,0,1,1,0,1,0,0.471429,0.230700,0.447661
1469,34,628,8,3,1,2,4,2,3,2,...,1,0,1,1,0,1,0,0.742857,0.178778,0.326601

In [10]:
y=df["DailyRate"]
df.drop("DailyRate",axis=1,inplace=True)
y

0       1102
1        279
2       1373
3       1392
4        591
        ...
1465     884
1466     613
1467     155
1468    1023
1469     628
Name: DailyRate, Length: 1470, dtype: int64

In [11]:
X=df
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=20)

In [12]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(random_state=16)
logreg.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(random_state=16)

In [14]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf = clf.fit(X_train,y_train)

In [13]:
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(n_estimators=50)
rf_model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=50)

In [15]:
lrpred=logreg.predict(X_test)
clfpred=clf.predict(X_test)
rfpred=rf_model.predict(X_test)

In [16]:
preddata= pd.DataFrame({'Y_test': y_test, 'Logistic Regression': lrpred, 'Decision Tree Classifier':clfpred, 'Random Forest': rfpred})
preddata

      Y_test  Logistic Regression  Decision Tree Classifier  Random Forest
1261     833                  896                      1124            167
434     1274                  495                      1296            294
313      553                  231                       359            430
1182     894                  667                       845            926
446      267                 1318                      1375            717
...      ...                  ...                       ...            ...
1059     660                  727                       793            890
1374     605                  836                      1351           1089
326      672                 1246                      1157            469
283      147                  279                      1252            135
855      977                 1069                      1389            859

[294 rows x 4 columns]

In [17]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, accuracy_score

In [18]:
mse = mean_squared_error(y_test, lrpred)
rmse = mean_squared_error(y_test, lrpred, squared=False)
mae = mean_absolute_error(y_test, lrpred)
r2 = r2_score(y_test, lrpred)
print("Logistic Regression")
print("MSE: ", mse)
print("RMSE: ", rmse)
print("MAE: ", mae)
print("R2: ", r2)

Logistic Regression
MSE:  306980.61904761905
RMSE:  554.0583173706709
MAE:  442.0408163265306
R2:  -0.7809471780959332

In [19]:
mse = mean_squared_error(y_test, clfpred)
rmse = mean_squared_error(y_test, clfpred, squared=False)
mae = mean_absolute_error(y_test, clfpred)
r2 = r2_score(y_test, clfpred)
print("Decision Tree Classifier")
print("MSE: ", mse)
print("RMSE: ", rmse)
print("MAE: ", mae)
print("R2: ", r2)

Decision Tree Classifier
MSE:  320337.9557823129
RMSE:  565.984059653903
MAE:  456.15986394557825
R2:  -0.8584397287277374

In [20]:
mse = mean_squared_error(y_test,  rfpred)
rmse = mean_squared_error(y_test,  rfpred, squared=False)
mae = mean_absolute_error(y_test,  rfpred)
r2 = r2_score(y_test,  rfpred)
print("Random Forest")
print("MSE: ", mse)
print("RMSE: ", rmse)
print("MAE: ", mae)
print("R2: ", r2)

Random Forest
MSE:  356305.7108843537
RMSE:  596.9134869345421
MAE:  471.7040816326531
R2:  -1.0671065564582811